version: '3'

tasks:
  server:add:
    desc: Set up a new server configuration
    cmds:
      - bash scripts/tasks/server-add.sh

  service:add:
    desc: Add a new service to the current server
    cmds:
      - bash scripts/tasks/service-add.sh

  up:
    desc: Start proxy and myapp services
    cmds:
      - docker compose -f proxy/docker-compose.yml up -d
      - docker compose -f apps/myapp/docker-compose.yml up -d

  set-domain:
    desc: Set domain value and run config script
    vars:
      DOMAIN: PLACEHOLDER
    cmds:
      - bash set-config-domain.sh {{.DOMAIN}}

  down:
    desc: Stop proxy and myapp services
    cmds:
      - docker compose -f apps/myapp/docker-compose.yml down
      - docker compose -f proxy/docker-compose.yml down


