services:
  whoami:
    image: traefik/whoami
    container_name: enmeduranki-whoami
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`enmeduranki.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.service=whoami-svc"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=lehttp"
      - "traefik.http.middlewares.whoami-headers.headers.stsSeconds=31536000"
      - "traefik.http.routers.whoami.middlewares=whoami-headers@docker"
      - "traefik.http.routers.whoami-http.service=whoami-svc"
      - "traefik.http.routers.whoami-http.rule=Host(`enmeduranki.com`)"
      - "traefik.http.routers.whoami-http.entrypoints=web"
      - "traefik.http.routers.whoami-http.middlewares=whoami-https-redirect"
      - "traefik.http.middlewares.whoami-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
