use_default_settings:
  engines:
    remove:
      - wikidata

general:
  debug: false
  instance_name: "fused-searxng"
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en-US"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "changeme"
  limiter: false
  image_proxy: false
  http_protocol_version: "1.0"
  method: "GET"

valkey:
  url: redis://fused-valkey:6379/0

outgoing:
  request_timeout: 10.0
  max_request_timeout: 30.0

engines:
  - name: google
    engine: google
    shortcut: g
    use_mobile_ui: false
  - name: bing
    engine: bing
    shortcut: b
  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
